### PR TITLE
Code Reformatting

### PR DESCRIPTION
**Pull request by Zeus3101**
There are some major code changes. Mainly in the DQN utils.py file and the Common buffers.py files. Changed PrioritizedReplay to use deque and added a helper function in utils.py to add customizability to use fully connected and noisy layers together. There's some reformatting done here and there other than variable name changes, blank line and line length corrections.

Still have to go through a lot of code. Let me know if changes along these lines are fine.

### CODE REVIEW

**Comment by Zeus3101** [comment]
Yeah, that's fine. Also, how exactly do you improve code coverage? I could try doing it while reformatting if it helps.

**Comment by ajaysub110** [comment]
Code coverage is the percentage of code tested. So to increase, it we've to add more tests. I think it would be better if that could be done as a separate PR though

**Comment by Sharad24** [comment]
By adding tests for functions, classes, etc. You can check how much of each file is covered here: https://codecov.io/gh/SforAiDl/JigglypuffRL <https://codecov.io/gh/SforAiDl/JigglypuffRL>

**Comment by Zeus3101** [comment]
Ok nvm, I thought it could be improved by adding documentation.

**Comment by Zeus3101** [comment]
Any other changes? I was considering revamping the save/load to make it use get_hyperparams instead. Should I instead do it in another PR?

**Comment by Zeus3101** [comment]
I guess it could be implemented better with the Trainer class so maybe after that?

**Comment by Sharad24** [comment]
Are you still working on this?

**Comment by Zeus3101** [comment]
Few key changes:
- Changed Prioritized Buffer to use deque
- Added `noisy_mlp` function, analogous to the `mlp` function. Makes customising Noisy layers easier and cleaner
- Reformatted code

**Comment by Sharad24** [comment]
Push a useless commit to build Travis CI and Codecov again

**Comment by Sharad24** [comment]
Will merge this today. Can you resolve the conflicts. Created due to merging #106

**Comment by Sharad24** [comment]
Is this done?

**Comment by Zeus3101** [comment]
Yeah

**Comment by Zeus3101** [comment]
You can merge it now

**Comment by Sharad24** [comment]
Hmm codecov fails. I guess thats happening cause of the extra cuda statements somwhere (and travis not being able to run them).

**Pull request merged**
