### PR TITLE
add Precommit checks

### PR DESCRIPTION
**Pull request by ajaysub110**
#135

### CODE REVIEW

**Comment by ajaysub110** [comment]
Should we also have a flake8 check or is black enough?

**Comment by Sharad24** [comment]
For flake 8 we'd need to do a massive overhaul

**Comment by Sharad24** [comment]
Dont we also have to update Travis? With a `black --check genrl`?

https://github.com/SforAiDl/decepticonlp/blob/64f99917915763d709f808def4187c145cd67a5a/.travis.yml#L16

**Comment by ajaysub110** [comment]
Yeah, seems inconvenient. Maybe we'll add it later in the release branch?

**Comment by Sharad24** [comment]
> Yeah, seems inconvenient. Maybe we'll add it later in the release branch?

Yeah, sounds good

**Pull request merged**
