### PR TITLE
Add Test DQN

### PR DESCRIPTION
**Pull request by Het-Shah**
Added 1 test as of now. I'll add for all variants.

### CODE REVIEW

**Comment by Sharad24** [comment]
Have you tried running this locally? Also, can you push a fake commit to trigger the Travis CI again?

**Comment by Sharad24** [comment]
Add this in front of `learn` method of `DQN`: `# pragma: no cover`

**Comment by ajaysub110** [comment]
Travis can be retriggered by clicking restart build on travis-ci.com

**Comment by Het-Shah** [comment]
> Add this in front of learn method of DQN: # pragma: no cover 

I'll add this

**Comment by Het-Shah** [comment]
will have to modify `OffPolicyTrainer` for incorporating prioritized replay buffer and some other stuff.

**Comment by Het-Shah** [comment]
DQN, Double DQN is training on CartPole properly now. Still running for prioritized replay and all.

**Comment by Sharad24** [comment]
Anything else to add?

**Comment by Het-Shah** [comment]
yea this is just double dqn's test 
I'll add for prioritized_replay and categorical one also.

**Comment by Sharad24** [comment]
Ok

**Comment by Het-Shah** [comment]
I guess I have added all the tests for DQN now. Let me know if any more tests are needed.

**Comment by Sharad24** [comment]
Merging.

**Pull request merged**
