### PR TITLE
imports in deep/common wrt #203

### PR DESCRIPTION
**Pull request by IshanDaga**
Fixed the imports for the agents under `genrl/deep/agents` to make sure I'm doing the right thing.
Still a little unsure of the changes to be made under `genrl/deep/common/__init__.py`

### CODE REVIEW

**Comment by sampreet-arthi** [comment]
Looks good. So check if there are other files that have the same problem (all files in genrl/deep at least). 

As for the `__init__.py`, go to `genrl/deep/common/__init__.py` and remove all the imports there that shouldn't be accessible outside of their own files. 

For example, one shouldn't be able to say do `from genrl.deep.common import get_env_properties`. Then you would remove it's import in `genrl/deep/common/__init__.py`

**Comment by sampreet-arthi** [comment]
Also, use precommit. You can install it with `pip install precommit` and then run `pre-commit install` in the root directory. So whenever you commit, it'll take care of the linting.

**Comment by sampreet-arthi** [comment]
Please mark this with a [WIP] or change it to a draft PR if you're not ready for a review yet.

**Comment by Sharad24** [comment]
Resolve conflicts?

**Comment by threewisemonkeys-as** [comment]
Looks good. @sampreet-arthi I think we can merge?

**Comment by sampreet-arthi** [comment]
Yep, looks good. @IshanDaga if you're done, we can merge this.

**Comment by IshanDaga** [comment]
Yep. Everything under deep/common had been checked and fixed

**Comment by sampreet-arthi** [comment]
Good job, thanks for the PR!

**Pull request merged**
