### PR TITLE
Updated logger.py

### PR DESCRIPTION
**Pull request by Darshan-ko**
Fixed KeyError in genrl/deep/common/logger.py .
Issue #192

### CODE REVIEW

**Comment by Darshan-ko** [comment]
Sorry I did not understand. Let the user have control over what?

**Comment by Sharad24** [comment]
Over which key is selected in TensorboardLogger for the x-axis. Right now its hard-coded to "timestep".

**Comment by Darshan-ko** [comment]
Ok got it.

**Comment by Darshan-ko** [comment]
So the user should have an option of either "episode" or "timestep" on the x axis (or also the various losses)?

**Comment by Sharad24** [comment]
The user should have an option of either "episode" or "timestep" on the x
axis

**Pull request closed without merging**
