### PR TITLE
[WIP] gym.vector integration

### PR DESCRIPTION
**Pull request by Het-Shah**
The integration won't be that tough. Our codebase is compatible mostly with gym.vector, we only need to take care of some shape issues. I have tried this on PPO1. I trained PPO1 with CartPole-v0 and it is converging. 

Any thoughts on this @Sharad24 @ajaysub110

### CODE REVIEW

**Comment by Het-Shah** [comment]
The original functions are `fun_2()`. They are for your reference so as to see what changes are there.

**Comment by ajaysub110** [comment]
Yeah shape issues are the main thing. The 2d array that env.observation_space returns needs to be flattened for our model.
For action, gym.vector returns a tuple of actions, so we'll need to see how to handle that

**Comment by Het-Shah** [comment]
> Yeah shape issues are the main thing. The 2d array that env.observation_space returns needs to be flattened for our model.
For action, gym.vector returns a tuple of actions, so we'll need to see how to handle that

Yea I don't think it is creating any problems as of now have a look at the code once

**Comment by Het-Shah** [comment]
Sorry, I forgot to add the code that I used to run this. You can use the following code.
`env=gym.vector.make("CartPole-v0",2)`
`PPO1("mlp",env)`
`trainer = OnPolicyTrainer(algo, env, log_mode=["stdout"], logdir="./logs", epochs=100)`
`trainer.train()`

**Comment by Het-Shah** [comment]
Yup, we need to take care of shapes more or less.

**Comment by Het-Shah** [comment]
Should we do this for all agents now?

**Comment by Sharad24** [comment]
Yup

**Comment by Het-Shah** [comment]
Cool, I'll start then.

**Comment by Het-Shah** [comment]
Closing this as we are not going ahead with `gym.vector`.

**Pull request closed without merging**
