### PR TITLE
The much awaited name change

### PR DESCRIPTION
**Pull request by ajaysub110**
Changed:
`jigglypuffRL` - `genrl`
`jigglypuff-rl` - `genrl`
`classicalrl` - `classical`
`deeprl` - `deep`

### CODE REVIEW

**Comment by ajaysub110** [comment]
Will add tests and merge after #96 is merged

**Comment by Sharad24** [comment]
Can you change things in the `docs/source/conf.py` as well?

**Comment by ajaysub110** [comment]
Yeah, there are a lot of changes to be made apart from that also

**Comment by Sharad24** [comment]
Ok

**Comment by Sharad24** [comment]
I'm able to build documentation and see all modules locally. I think its the name thats conflicting now

**Comment by ajaysub110** [comment]
Okay, let's see if it works after this

**Comment by Sharad24** [comment]
Going through the modules we're pretty much importing everything into the main package which we should change probably in the future

**Comment by Sharad24** [comment]
I think you'd have to merge it see the docs, they might not be visible on your fork's website?

**Comment by ajaysub110** [comment]
But in order to solve merge conflicts, I pulled from master, so I should be able to see it right?

**Pull request merged**
