### PR TITLE
Value iteration

### PR DESCRIPTION
**Pull request by hades-rp2010**
Wrt #357 
Havent added a test yet, added the value iteration file as `genrl/agents/classical/valueiteration/valueiteration.py`. Can be trained with the current Classical trainer

### CODE REVIEW

**Review by Sharad24 — CHANGES_REQUESTED** [review]
Few comments:
- It might be worth coming up with a general design for Model Based Agents. 
- Value Iteration can happen with DNNs as well.

**Review by Sharad24 — COMMENTED** [review]
Does the agent train?

**Comment by hades-rp2010** [comment]
> Few comments:
> 
> * It might be worth coming up with a general design for Model Based Agents.
> * Value Iteration can happen with DNNs as well.

1. Since this is a classical method, I didn't include the base model based agent here, its in my CEM PR
2. This is on hold

So I guess this is all for the classical VI

**Comment by hades-rp2010** [comment]
> Does the agent train?

It did before, I'll run it again and check

**Comment by hades-rp2010** [comment]
> Does the agent train?

Yes it does train on FrozenLake

**Comment by Sharad24** [comment]
Ok great. Any comparison with Q Learning?

Will merge it post CI re-run

**Pull request merged**
