### PR TITLE
Add Typing

### PR DESCRIPTION
**Pull request by Het-Shah**
#136

### CODE REVIEW

**Comment by Het-Shah** [comment]
This is going to be a pretty long one, feel free to push to this

**Comment by Sharad24** [comment]
Files in classical and TD3 left?

**Comment by Het-Shah** [comment]
Yes. I'll do it eventually it is just too boring to just add these.

**Comment by Het-Shah** [comment]
I have removed the evaluate function from utils because we shifted it to the trainer now. Now only classical is left.

**Comment by Het-Shah** [comment]
@Sharad24 I guess I am done with this, Bandits has been redone in another pr so I am not doing it here because then someone will have to redo it anyway.

**Comment by Sharad24** [comment]
Great, merging.

**Pull request merged**
