### PR TITLE
Trainer Max Timesteps

### PR DESCRIPTION
**Pull request by sampreet-arthi**
Currently, the Off Policy Trainer doesn't control how long the training should be efficiently. User can specify `epochs` and `max_ep_len` but there should be some easier way to cap how long training takes by giving an additional option to just cap the timesteps.

### CODE REVIEW

**Comment by sampreet-arthi** [comment]
Why's one of the build showing the grey warning symbol? I can't seem to see the full log for that

**Comment by Sharad24** [comment]
Cant see anything

**Comment by sampreet-arthi** [comment]
Nvm, it ran on it's own. Must have been some gh-actions side error. Can we merge this?

**Review by Sharad24 — APPROVED** [review]
Looks good

**Pull request merged**
