### PR TITLE
Added documentation

### PR DESCRIPTION
**Pull request by Zeus3101**
Redoing #112 as that seemed to have unusual build errors.

### CODE REVIEW

**Comment by Sharad24** [comment]
Good to merge?

**Comment by Zeus3101** [comment]
Yeah, I'll add docs for classical after bandits file gets separated according to the issue.

**Comment by Zeus3101** [comment]
This is good to merge @Sharad24

**Comment by Zeus3101** [comment]
Only documentation has been added so codecov is not relevant

**Pull request merged**
