### PR TITLE
Pytorch style docs

### PR DESCRIPTION
**Pull request by Sharad24**

### CODE REVIEW

**Comment by Sharad24** [comment]
@ajaysub110 Can you check this once? I'm not sure if I'm doing it correctly

**Comment by ajaysub110** [comment]
`_static` and `_templates` directories don't seem to be there within docs. So, I'm not able to run `make html`. Did you use `sphinx-quickstart`. If not, check this out: https://medium.com/@eikonomega/getting-started-with-sphinx-autodoc-part-1-2cebbbca5365

**Comment by Sharad24** [comment]
Am I supposed to push the folder in which the site is built? Or the source files? If the source files are supposed to be pushed, how does github know how to build docs and where the build directory is?

**Comment by Sharad24** [comment]
Ok, I think I figured this out. We either need to build locally and then push only the build folder which has all the html files. Or we need to setup a workflow for building with [circleci](https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/)

**Comment by ajaysub110** [comment]
Do you want to set up circleci now itself? We'll be able to put docs status as a badge too then

**Comment by Sharad24** [comment]
Hmm no I'm just thinking of using travis CI for this since they'd be the same essentially

**Comment by ajaysub110** [comment]
Oh, I didn't Travis had the features. Sounds good

**Comment by Sharad24** [comment]
Just running it as a job in the CI, so I think it should work

**Comment by Sharad24** [comment]
Going to merge this and push some commits to master to get it working

**Comment by Sharad24** [comment]
It worked!!!
[Check it out](https://sforaidl.github.io/genrl/)

**Comment by Sharad24** [comment]
You can run `sphinx-versioning --use-master-conf --use-master-templates build --greatest-tag --whitelist-branches master docs/source docs/build/html` to build documentation locally. And see why its not showing anything

**Pull request merged**
