### PR TITLE
Absolute imports

### PR DESCRIPTION
**Pull request by duttaANI**
Folders modified :

- genrl/deep/agents

- genrl/classical

### CODE REVIEW

**Comment by sampreet-arthi** [comment]
Is this done @duttaANI or are you still adding to this?

**Comment by duttaANI** [comment]
> Is this done @duttaANI or are you still adding to this?

I will add absolute imports to common files

**Comment by Sharad24** [comment]
Mark the PR as a draft OR or add a tag '[WIP]' if you're stlil working on it.

**Comment by duttaANI** [comment]
I believe the task is complete, just checked if I have covered all the files in genrl folder.

**Comment by sampreet-arthi** [comment]
Yeah, looks like everything's covered. Good job!

**Comment by sampreet-arthi** [comment]
@duttaANI you'll need to install pre-commit and sort out lint errors. Just do `pip install pre-commit` and `pre-commit install` from the genrl root directory. After that push some minor commit and then the linting changes will be automatically done by pre-commit.

**Pull request merged**
