### PR TITLE
Add GA example

### PR DESCRIPTION
**Pull request by mehulrastogi**

### CODE REVIEW

**Comment by Sharad24** [comment]
Nice! Awesome

@mehulrastogi Can you resolve the LGTM alerts? There's 8 of them, they should be fairly easy to resolve

**Comment by mehulrastogi** [comment]
Yup will resolve LGTM issues. Although I cant really cover codeclimate. Also, can you look at lint test failing?

**Comment by Sharad24** [comment]
Should be fixed now. Coverage might still fail as we don't have a test for GA

**Comment by Sharad24** [comment]
I'll fix the test can you work on the tutorial until then?

**Comment by Sharad24** [comment]
Why is LGTM failing?

**Comment by mehulrastogi** [comment]
Even I don't know why the LGTM is failing. Let me take a look. Also, any improvement required in the GA tutorial?

**Comment by Sharad24** [comment]
Closing. Merged this with #256 (as LGTM was failing here)

**Pull request closed without merging**
