### PR TITLE
Using utils.save_params() in trainer instead of save()

### PR DESCRIPTION
**Pull request by ajaysub110**
#137

### CODE REVIEW

**Comment by ajaysub110** [comment]
@Zeus3101

**Comment by Sharad24** [comment]
@ajaysub110 Lets merge this?

**Comment by ajaysub110** [comment]
I'll fix the LGTM alert and then we'll merge?

**Comment by Sharad24** [comment]
Sg!

**Comment by Sharad24** [comment]
@ajaysub110 Are you also working on #143 here?

**Comment by ajaysub110** [comment]
Nope, I'll open another PR for that

**Comment by Zeus3101** [comment]
What's with the codecov? Is this ready to merge?

**Comment by Sharad24** [comment]
Should be good to merge

**Pull request merged**
