### PR TITLE
[WIP] Atari Actor Critic

### LINKED ISSUE #166: Add atari support for Actor Critic
Created as part of #128﻿

### PR DESCRIPTION
**Pull request by sampreet-arthi**
Resolves #166 

Changes:
- Added a `CNNActorCritic` with a convolutional feature layer and separate policy and value functions within
- Refactored PPO1 to work with ActorCritic instead of `policy_new` and `value_fn`
- Modified `get_env_properties` to return `input_dim` instead of `state_dim` which will be `framestack` in the case of Atari envs and the state space shape everywhere else.
- Atari support enabled for DQN, A2C and PPO1

Problems:
- A2C and PPO1 are giving out `nan`s for rewards every 2-3 episodes. These don't train at all as of now.

### CODE REVIEW

**Comment by sampreet-arthi** [comment]
Added Atari support for PPO1, A2C and VPG. None of them seem to train well. Will track this in #185 instead after merging this. There might be an issue with VecNormalize. Will sort after #183

**Comment by sampreet-arthi** [comment]
Ready to merge @Sharad24 @ajaysub110

**Comment by Sharad24** [comment]
Will merge this, but can you add an atari example in the documentation?

And anything else you've added.

**Comment by sampreet-arthi** [comment]
> Will merge this, but can you add an atari example in the documentation?

> And anything else you've added.

Yeah sure. Should I add it here itself?

**Comment by sampreet-arthi** [comment]
> And anything else you've added

Nothing major other than the Atari functionality. We can added docs explaining how to add new policies.

**Comment by Sharad24** [comment]
LGTM alerts?

**Comment by Sharad24** [comment]
Lol

**Comment by sampreet-arthi** [comment]
Now? Removed the unused import, the other alert can be ignored.

**Pull request merged**
