### PR TITLE
Code duplication with get_env_properties

### PR DESCRIPTION
**Pull request by Zeus3101**
Put method `get_env_properties` inside utils.py in common because the same function was being used everywhere.

### CODE REVIEW

**Comment by Het-Shah** [comment]
Don't put it in `utils.py`, rather put it in the trainer class.

**Comment by Zeus3101** [comment]
If I put it in the Trainer class, then the agent files like `ddpg.py` etc won't work standalone.

**Comment by ajaysub110** [comment]
Why didn't codecov run?

**Comment by ajaysub110** [comment]
I think we can merge

**Pull request merged**
