### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by Sharad24**

### CODE REVIEW

**Comment by mehulrastogi** [comment]
Is modifying requirements.txt needed to simplify the requirements? First removing the included libraries like instead of strict == having >= might be sufficient. Also removing any repeated libraries might clean it up. For eg. for scipy one needs numpy so no need to explicitly mention it.

**Comment by Sharad24** [comment]
Some libraries break backwards compatibility e.g. isort 5.0.0 is not compatible with 4.3.2, which is why we have ==

**Comment by Sharad24** [comment]
We could remove already installed libraries, buts it's a very minor issue I guess.

Could be fixed in any PR, I suppose

**Comment by Sharad24** [comment]
We could keep >= for all except isort

**Pull request merged**
